$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: mlops-workshop-endpoint
model: azureml:nyc_fare_prediction:1
code_configuration:
  code:
    local_path: ./
  scoring_script: score.py
environment:
  conda_file: ./conda.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20210727.v1
instance_type: Standard_DS3_V2
instance_count: 1