$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: mlops-workshop-endpoint-njs-1 #setup replace `mlops-workshop-endpoint` with your own endpoint name defined in endpoint.yml
model: azureml:nyc_fare_prediction:latest
code_configuration:
  code: ./
  scoring_script: score.py
environment:
  conda_file: ./conda.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20210727.v1
instance_type: Standard_DS2_V2
instance_count: 1
