name: my_workshop-ci
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: 
    - integration
    paths:
      - src/workshop/core/**
      - .github/workflows/my_workshop_ci.yml
jobs:
  Workshop-Train-Validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax 
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine
      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MY_AZURE_CREDENTIALS }}      #Setup

      - name: Install az ml & set default values for AML
        run: | #Setup
          az extension add -n ml -y
          az configure --defaults group=GROUP_NAME workspace=WORKSPACE_NAME location=LOCATION  
      - name: run training and model validation
        run: |
         az ml job create -s -f src/workshop/core/pipelines/my_training_pipeline.yml

      - name: Create Pull Request to Main
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.MY_GITHUB_SECRET }}   #Setup



