name: my-workshop-cd
on:
  workflow_dispatch:
  # setup
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine

      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MY_AZURE_CREDENTIALS }} #setup to point to your GitHub secret

      - name: Install az ml & and tools
        run: |
          az extension add -n ml -y
          sudo apt install jq
          pip install yq
      
      - name: Run deployment
        uses: ./.github/actions/aml-endpoint-deploy
        with:
          resourceGroup: #setup
          workspaceName: #setup
          endpointFile: src/workshop/core/scoring/my_endpoint.yml
          deploymentFile: src/workshop/core/scoring/my_deployment.yml
          modelVersion: latest
      
      - name: Test deployment
        uses: ./.github/actions/aml-endpoint-test
        with:
          resourceGroup: #setup
          workspaceName: #setup
          endpointFile: src/workshop/core/scoring/my_endpoint.yml
          requestFile: src/workshop/core/scoring/scoring_test_request.json
  
      - name: Swap deployment
        uses: ./.github/actions/aml-endpoint-swap
        with:
          resourceGroup: #setup
          workspaceName: #setup
          endpointFile: src/workshop/core/scoring/my_endpoint.yml