name: workshop-ci-train
on:
  workflow_dispatch:
  push:
    branches: 
      - integration
    paths:
      - src/workshop/core/**
      - .github/workflows/workshop_ci_train.yml

env:
  group: mtcs-ezmlops-rg
  workspace: ycmlops9aml
  location: westeurope
  compute: ycmlops9cbuu
  model: nyc_fare_prediction


jobs:
  Workshop-Train-Validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax test ci
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine
      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_YUENCHE }}   #setup: provide your Azure credentials name stored in github

      - name: Install az ml & set default values for AML
        run: | #setup: provide group, workspace and location
          az extension add -n ml -y
          az configure --defaults group=${{ env.group }} workspace=${{ env.workspace }} location=${{ env.location }} 
      - name: run training and model validation
        run: |
         az ml job create -s -f src/workshop/core/pipelines/training_pipeline.yml --set compute=${{ env.compute }}

  Model-Version:
    if: ${{ success() }}
    needs: [Workshop-Train-Validation]
    runs-on: ubuntu-latest
    steps:      
      - name:  list the model versions
        run: |
         az ml model list --resource-group ${{ env.group }} --workspace-name ${{ env.workspace }} --name ${{ env.model }}

