name: workshop-cd
on:
  workflow_dispatch:
  workflow_run:
    workflows: [workshop-ci]
    branches: [integration]
    types:
      - completed
  pull_request:
    branches: 
    - main
    paths:
      - src/workshop/core/scoring/*
      - .github/workflows/workshop_cd.yml
jobs:
  Workshop-Deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax 

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine

      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install az ml & and tools
        run: |
          az extension add -n ml -y
          sudo apt install jq
          pip install yq
      
      - name: Run deployment
        uses: ./.github/actions/aml-endpoint-deploy
        with:
          resourceGroup: mlops
          workspaceName: mlopsdev
          endpointFile: src/workshop/core/scoring/endpoint.yml
          deploymentFile: src/workshop/core/scoring/deployment.yml
          modelVersion: latest
      
      - name: Test deployment
        uses: ./.github/actions/aml-endpoint-test
        with:
          resourceGroup: mlops
          workspaceName: mlopsdev
          endpointFile: src/workshop/core/scoring/endpoint.yml
          requestFile: src/workshop/core/scoring/scoring_test_request.json
  
      - name: Swap deployment
        uses: ./.github/actions/aml-endpoint-swap
        with:
          resourceGroup: mlops
          workspaceName: mlopsdev
          endpointFile: src/workshop/core/scoring/endpoint.yml